addSbtPlugin("com.eed3si9n"  % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.9")
addSbtPlugin("io.spray"      % "sbt-revolver"  % "0.9.1")
addSbtPlugin("org.typelevel" % "sbt-tpolecat"  % "0.5.0")
